spring:
  application:
    name: testRds

  thymeleaf:
    cache: false
    check-template: true
    prefix: classpath:templates/
    suffix: .html

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  cloud:
    gcp:
      project-id: graphite-ruler-366202
      topic-name: testPub-sub
      topic-name-sub: testPub-sub-sub
      credentials:
        location: file:C:\Users\jcho5\Documents\PubSub_Account_Key.json

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

    #url: jdbc:mariadb://localhost:3306/test
    #driver-class-name:  org.mariadb.jdbc.Driver
    #username: root
    #password: 1234

#   url: jdbc:mariadb://database-1.cmdh7ovqnvel.ap-northeast-2.rds.amazonaws.com:3306/test
#   driver-class-name:  org.mariadb.jdbc.Driver
#   username: admin
#   password: 98989898

  jpa:
    hibernate:
      ddl-auto: create-drop
      #naming:
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    generate-ddl: true

logging:
  level:
    org.springframework.web : debug